import React, { useState, useEffect, useMemo } from "react";
import { payrollApi } from "../../api/payroll";
import { formatCurrency } from "../../utils/currency";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faMoneyBill,
  faCheck,
  faCreditCard,
  faSpinner,
  faRefresh,
  faDownload,
} from "@fortawesome/free-solid-svg-icons";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
} from "recharts";
import "./PayrollManagement.css";

// Notification helper for payroll events
const createPayrollNotification = async (message, priority = "high") => {
  try {
    await fetch("http://127.0.0.1:8000/api/notifications", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${localStorage.getItem("token")}`,
      },
      body: JSON.stringify({
        type: "payroll",
        message,
        priority,
        role: "manager",
      }),
    });
  } catch (error) {
    console.warn("Notification failed:", error);
  }
};

const PayrollManagement = () => {
  const [payrolls, setPayrolls] = useState([]);
  const [summary, setSummary] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedPeriod, setSelectedPeriod] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [generating, setGenerating] = useState(false);

  // Fetch payrolls
  const fetchPayrolls = async () => {
    try {
      setLoading(true);
      const response = await payrollApi.getAll();
      setPayrolls(response.data || []);
      setSummary(response.summary || null);
      setError("");
    } catch (err) {
      setError(err.message || "Failed to load payroll data");
      console.error("Payroll fetch error:", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchPayrolls();
  }, []);

  // Generate payroll for period
  const handleGenerate = async () => {
    if (!startDate || !endDate) {
      alert("Please select both start and end dates");
      return;
    }

    if (new Date(startDate) > new Date(endDate)) {
      alert("Start date must be before end date");
      return;
    }

    setGenerating(true);

    try {
      await payrollApi.generateForPeriod({
        start_date: startDate,
        end_date: endDate,
      });

      await createPayrollNotification(
        `Payroll generated for ${startDate} to ${endDate}`,
        "high"
      );

      await fetchPayrolls();
      setStartDate("");
      setEndDate("");
    } catch (err) {
      alert(err.message || "Failed to generate payroll");
    } finally {
      setGenerating(false);
    }
  };

  // Approve payroll
  const handleApprove = async (id) => {
    try {
      await payrollApi.approve(id);

      await createPayrollNotification(
        `Payroll #${id} has been approved`,
        "medium"
      );

      await fetchPayrolls();
    } catch (err) {
      alert(err.message || "Failed to approve payroll");
    }
  };

  // Mark payroll as paid
  const handlePaid = async (id) => {
    try {
      await payrollApi.markAsPaid(id);

      await createPayrollNotification(
        `Payroll #${id} has been marked as PAID`,
        "high"
      );

      await fetchPayrolls();
    } catch (err) {
      alert(err.message || "Failed to mark as paid");
    }
  };

  // Download payslip as PDF
  const downloadPayslip = (payroll) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(18);
    doc.setTextColor(255, 95, 147);
    doc.text("Pawesome Payroll - Payslip", 14, 20);

    // Company info
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Pawesome Pet Services", 14, 28);
    doc.text("Generated by Payroll Management System", 14, 33);

    // Employee info
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Employee: ${payroll.user?.name || "N/A"}`, 14, 45);
    doc.text(`Payroll ID: ${payroll.payroll_id || "N/A"}`, 14, 52);
    doc.text(`Pay Period: ${payroll.pay_period_label || "N/A"}`, 14, 59);
    doc.text(`Status: ${(payroll.status || "N/A").toUpperCase()}`, 14, 66);

    // Earnings & Deductions Table
    autoTable(doc, {
      startY: 75,
      head: [["Description", "Details", "Amount"]],
      body: [
        ["EARNINGS", "", ""],
        ["Regular Hours", `${payroll.regular_hours || 0} hrs`, ""],
        ["Overtime Hours", `${payroll.overtime_hours || 0} hrs`, ""],
        ["Gross Pay", "", formatCurrency(payroll.gross_pay)],
        ["", "", ""],
        ["DEDUCTIONS", "", ""],
        ["Late/Absence Deductions", `${payroll.late_count || 0} late / ${payroll.absent_count || 0} absent`, formatCurrency(payroll.deductions)],
        ["", "", ""],
        ["NET PAY", "", formatCurrency(payroll.net_pay)],
      ],
      headStyles: {
        fillColor: [255, 95, 147],
        textColor: 255,
        fontStyle: "bold",
      },
      bodyStyles: {
        fontSize: 10,
      },
      alternateRowStyles: {
        fillColor: [250, 250, 250],
      },
      columnStyles: {
        0: { fontStyle: "bold", cellWidth: 60 },
        1: { cellWidth: 70 },
        2: { halign: "right", fontStyle: "bold" },
      },
      footStyles: {
        fillColor: [255, 95, 147],
        textColor: 255,
        fontStyle: "bold",
      },
    });

    // Footer
    const finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text("This is an official payslip generated by Pawesome Payroll System.", 14, finalY);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, finalY + 5);

    // Save
    const filename = `Payslip-${payroll.user?.name?.replace(/\s+/g, "_") || "employee"}-${payroll.pay_period_label?.replace(/\s+/g, "_") || "period"}.pdf`;
    doc.save(filename);
  };

  // Filter payrolls
  const filteredPayrolls = useMemo(() => {
    let filtered = payrolls;

    if (searchTerm) {
      filtered = filtered.filter(
        (p) =>
          p.payroll_id?.toLowerCase().includes(searchTerm.toLowerCase()) ||
          p.user?.name?.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    if (selectedPeriod) {
      filtered = filtered.filter((p) => p.pay_period_label === selectedPeriod);
    }

    return filtered;
  }, [payrolls, searchTerm, selectedPeriod]);

  // Unique pay periods for filter
  const payPeriods = useMemo(() => {
    const periods = [...new Set(payrolls.map((p) => p.pay_period_label))];
    return periods.sort().reverse();
  }, [payrolls]);

  const getStatusBadgeClass = (status) => {
    const classes = {
      paid: "status-paid",
      pending: "status-pending",
      processing: "status-processing",
      draft: "status-draft",
      approved: "status-approved",
      cancelled: "status-cancelled",
    };
    return classes[status] || "status-draft";
  };

  // Chart calculations
  const totalGross = payrolls.reduce((sum, p) => sum + Number(p.gross_pay || 0), 0);
  const totalNet = payrolls.reduce((sum, p) => sum + Number(p.net_pay || 0), 0);
  const totalDeductions = payrolls.reduce((sum, p) => sum + Number(p.deductions || 0), 0);
  const totalOvertime = payrolls.reduce((sum, p) => sum + Number(p.overtime_hours || 0), 0);

  const payrollChartData = payrolls.slice(0, 10).map((p) => ({
    name: p.user?.name?.split(" ")[0] || "Employee",
    gross: Number(p.gross_pay || 0),
    net: Number(p.net_pay || 0),
    deductions: Number(p.deductions || 0),
  }));

  const statusChartData = [
    {
      name: "Pending",
      value: payrolls.filter((p) => p.status === "pending").length,
      color: "#fbbf24",
    },
    {
      name: "Approved",
      value: payrolls.filter((p) => p.status === "approved").length,
      color: "#60a5fa",
    },
    {
      name: "Paid",
      value: payrolls.filter((p) => p.status === "paid").length,
      color: "#4ade80",
    },
  ];

  return (
    <div className="manager-payroll">
      <div className="payroll-header">
        <div className="header-left">
          <h1>Payroll Management</h1>
          <p>Manage employee payroll, process payments, and view salary summaries.</p>
        </div>
        <div className="header-actions">
          <button
            className="btn-refresh"
            onClick={fetchPayrolls}
            disabled={loading}
            title="Refresh data"
          >
            <FontAwesomeIcon icon={loading ? faSpinner : faRefresh} spin={loading} />
          </button>
        </div>
      </div>

      {/* Generate Payroll Section */}
      <div className="payroll-generate">
        <div className="generate-dates">
          <div className="date-input-group">
            <label>Start Date</label>
            <input
              type="date"
              value={startDate}
              onChange={(e) => setStartDate(e.target.value)}
              className="date-input"
            />
          </div>
          <div className="date-input-group">
            <label>End Date</label>
            <input
              type="date"
              value={endDate}
              onChange={(e) => setEndDate(e.target.value)}
              className="date-input"
            />
          </div>
        </div>
        <button
          className="btn-generate"
          onClick={handleGenerate}
          disabled={generating || !startDate || !endDate}
        >
          <FontAwesomeIcon icon={generating ? faSpinner : faMoneyBill} spin={generating} />
          {generating ? "Generating..." : "Generate Payroll"}
        </button>
      </div>

      {/* Summary Cards */}
      {summary && (
        <div className="stats-grid">
          <div className="stat-card">
            <div className="stat-info">
              <h3>{summary.total_employees}</h3>
              <p>Total Employees</p>
            </div>
          </div>

          <div className="stat-card gross">
            <div className="stat-info">
              <h3>{formatCurrency(summary.total_gross)}</h3>
              <p>Total Gross Pay</p>
            </div>
          </div>

          <div className="stat-card net">
            <div className="stat-info">
              <h3>{formatCurrency(summary.total_net)}</h3>
              <p>Total Net Pay</p>
            </div>
          </div>

          <div className="stat-card deductions">
            <div className="stat-info">
              <h3>{formatCurrency(summary.total_deductions)}</h3>
              <p>Total Deductions</p>
            </div>
          </div>

          <div className="stat-card paid">
            <div className="stat-info">
              <h3>{summary.paid_count}</h3>
              <p>Paid</p>
            </div>
          </div>

          <div className="stat-card pending">
            <div className="stat-info">
              <h3>{summary.pending_count + summary.processing_count}</h3>
              <p>Pending</p>
            </div>
          </div>
        </div>
      )}

      {/* Analytics Dashboard */}
      {payrolls.length > 0 && (
        <>
          <div className="payroll-summary-grid">
            <div className="payroll-summary-card">
              <h3>{formatCurrency(totalGross)}</h3>
              <p>Total Gross Pay</p>
            </div>

            <div className="payroll-summary-card">
              <h3>{formatCurrency(totalDeductions)}</h3>
              <p>Total Deductions</p>
            </div>

            <div className="payroll-summary-card">
              <h3>{formatCurrency(totalNet)}</h3>
              <p>Total Net Pay</p>
            </div>

            <div className="payroll-summary-card">
              <h3>{totalOvertime}</h3>
              <p>Total Overtime Hours</p>
            </div>
          </div>

          <div className="payroll-chart-grid">
            <div className="payroll-chart-card">
              <h3>Payroll Amount Overview</h3>

              <ResponsiveContainer width="100%" height={300}>
                <BarChart data={payrollChartData}>
                  <XAxis dataKey="name" tick={{ fontSize: 12 }} />
                  <YAxis tick={{ fontSize: 12 }} />
                  <Tooltip
                    formatter={(value) => formatCurrency(value)}
                    contentStyle={{
                      backgroundColor: "rgba(255, 255, 255, 0.95)",
                      borderRadius: "12px",
                      border: "1px solid rgba(255, 95, 147, 0.2)",
                    }}
                  />
                  <Bar dataKey="gross" fill="#ff8db5" name="Gross Pay" />
                  <Bar dataKey="net" fill="#4ade80" name="Net Pay" />
                  <Bar dataKey="deductions" fill="#fbbf24" name="Deductions" />
                </BarChart>
              </ResponsiveContainer>
            </div>

            <div className="payroll-chart-card">
              <h3>Payroll Status Distribution</h3>

              <ResponsiveContainer width="100%" height={300}>
                <PieChart>
                  <Pie
                    data={statusChartData}
                    dataKey="value"
                    nameKey="name"
                    outerRadius={100}
                    label
                  >
                    {statusChartData.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <Tooltip />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>
        </>
      )}

      {/* Filters */}
      <div className="search-filters">
        <div className="filter-group">
          <input
            type="text"
            placeholder="Search by name or payroll ID..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
        </div>

        <div className="filter-group">
          <select
            value={selectedPeriod}
            onChange={(e) => setSelectedPeriod(e.target.value)}
            className="period-select"
          >
            <option value="">All Pay Periods</option>
            {payPeriods.map((period) => (
              <option key={period} value={period}>
                {period}
              </option>
            ))}
          </select>
        </div>
      </div>

      {loading && (
        <div className="loading">
          <FontAwesomeIcon icon={faSpinner} spin />
          <span>Loading payroll data...</span>
        </div>
      )}
      {error && <div className="error-message">{error}</div>}

      {/* Payroll Table */}
      <div className="payroll-table-container">
        <table className="payroll-table">
          <thead>
            <tr>
              <th>Payroll ID</th>
              <th>Employee</th>
              <th>Pay Period</th>
              <th>Hours</th>
              <th>Overtime</th>
              <th>Gross Pay</th>
              <th>Deductions</th>
              <th>Net Pay</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            {filteredPayrolls.map((payroll) => (
              <tr key={payroll.id}>
                <td className="payroll-id">{payroll.payroll_id}</td>
                <td className="employee-name">{payroll.user?.name || "N/A"}</td>
                <td>{payroll.pay_period_label}</td>
                <td>{payroll.regular_hours || 0}</td>
                <td>{payroll.overtime_hours || 0}</td>
                <td>{formatCurrency(payroll.gross_pay)}</td>
                <td className="deductions">{formatCurrency(payroll.deductions)}</td>
                <td className="net-pay">{formatCurrency(payroll.net_pay)}</td>
                <td>
                  <span className={`status-badge ${getStatusBadgeClass(payroll.status)}`}>
                    {payroll.status}
                  </span>
                </td>
                <td className="actions">
                  {payroll.status === "pending" && (
                    <button
                      className="btn-action btn-approve"
                      onClick={() => handleApprove(payroll.id)}
                      title="Approve Payroll"
                    >
                      <FontAwesomeIcon icon={faCheck} />
                    </button>
                  )}
                  {payroll.status === "approved" && (
                    <button
                      className="btn-action btn-paid"
                      onClick={() => handlePaid(payroll.id)}
                      title="Mark as Paid"
                    >
                      <FontAwesomeIcon icon={faCreditCard} />
                    </button>
                  )}
                  {(payroll.status === "approved" || payroll.status === "paid") && (
                    <button
                      className="btn-action btn-download"
                      onClick={() => downloadPayslip(payroll)}
                      title="Download Payslip"
                    >
                      <FontAwesomeIcon icon={faDownload} />
                    </button>
                  )}
                  {payroll.status === "paid" && (
                    <span className="paid-badge">✓ Paid</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {filteredPayrolls.length === 0 && !loading && (
          <div className="no-results">No payroll records found.</div>
        )}
      </div>
    </div>
  );
};

export default PayrollManagement;
