export const inventoryItems = [
  {
    id: "INV-001",
    name: "Classic Crispy Burger",
    sku: "BUR-001",
    brand: "ClaPos Foods",
    supplier: "Fresh Foods Co.",
    category: "Burgers",
    price: 6.99,
    quantity: 24,
    expiration: "2025-12-10",
    status: "In stock",
  },
  {
    id: "INV-002",
    name: "Spicy Chicken Sandwich",
    sku: "CHX-001",
    brand: "ClaPos Premium",
    supplier: "Urban Farms",
    category: "Chicken",
    price: 7.49,
    quantity: 14,
    expiration: "2025-11-05",
    status: "Low stock",
  },
  {
    id: "INV-003",
    name: "Double Cheese Burger",
    sku: "BUR-002",
    brand: "ClaPos Foods",
    supplier: "Fresh Foods Co.",
    category: "Burgers",
    price: 8.25,
    quantity: 32,
    expiration: "2026-01-18",
    status: "In stock",
  },
  {
    id: "INV-004",
    name: "Chocolate Milkshake",
    sku: "DRK-001",
    brand: "ClaPos Drinks",
    supplier: "Cool Beverages Ltd.",
    category: "Drinks",
    price: 3.75,
    quantity: 46,
    expiration: "2026-02-12",
    status: "In stock",
  },
  {
    id: "INV-005",
    name: "Classic Fries",
    sku: "SID-001",
    brand: "ClaPos Sides",
    supplier: "Crispy Supplies",
    category: "Sides",
    price: 2.49,
    quantity: 62,
    expiration: "2026-03-15",
    status: "In stock",
  },
  {
    id: "INV-006",
    name: "Garden Salad",
    sku: "SAL-001",
    brand: "ClaPos Fresh",
    supplier: "Green Valley",
    category: "Salads",
    price: 4.99,
    quantity: 18,
    expiration: "2025-10-28",
    status: "Low stock",
  },
  {
    id: "INV-007",
    name: "Iced Coffee",
    sku: "DRK-002",
    brand: "ClaPos Drinks",
    supplier: "Cool Beverages Ltd.",
    category: "Drinks",
    price: 3.25,
    quantity: 52,
    expiration: "2026-04-10",
    status: "In stock",
  },
  {
    id: "INV-008",
    name: "Coca Cola Bottle",
    sku: "DRK-003",
    brand: "ClaPos Drinks",
    supplier: "Cool Beverages Ltd.",
    category: "Drinks",
    price: 3.0,
    quantity: 88,
    expiration: "2026-07-01",
    status: "In stock",
  },
  {
    id: "INV-009",
    name: "Chicken Nuggets",
    sku: "CHX-002",
    brand: "ClaPos Premium",
    supplier: "Golden Poultry",
    category: "Chicken",
    price: 5.49,
    quantity: 12,
    expiration: "2025-10-20",
    status: "Low stock",
  },
  {
    id: "INV-010",
    name: "Chocolate Cake Slice",
    sku: "DSR-001",
    brand: "ClaPos Desserts",
    supplier: "Sweet Treats Co.",
    category: "Desserts",
    price: 4.2,
    quantity: 28,
    expiration: "2026-01-08",
    status: "In stock",
  },
];

export const inventoryHistory = [
  {
    id: "HIS-001",
    date: "2026-03-30 09:45",
    product: "Classic Crispy Burger",
    action: "Restocked",
    quantity: 20,
    user: "Warehouse Team",
    note: "Weekly replenishment",
  },
  {
    id: "HIS-002",
    date: "2026-03-29 15:12",
    product: "Chicken Nuggets",
    action: "Sale",
    quantity: 18,
    user: "Cashier 05",
    note: "Lunch rush",
  },
  {
    id: "HIS-003",
    date: "2026-03-28 11:30",
    product: "Garden Salad",
    action: "Restocked",
    quantity: 10,
    user: "Warehouse Team",
    note: "Fresh greens delivery",
  },
  {
    id: "HIS-004",
    date: "2026-03-27 18:05",
    product: "Coca Cola Bottle",
    action: "Sale",
    quantity: 26,
    user: "Cashier 02",
    note: "Dinner service",
  },
  {
    id: "HIS-005",
    date: "2026-03-26 14:20",
    product: "Spicy Chicken Sandwich",
    action: "Restocked",
    quantity: 15,
    user: "Warehouse Team",
    note: "Afternoon replenishment",
  },
  {
    id: "HIS-006",
    date: "2026-03-25 10:10",
    product: "Chocolate Cake Slice",
    action: "Sale",
    quantity: 12,
    user: "Cashier 01",
    note: "Morning orders",
  },
];
