// Pet store inventory items only (₱ Philippine Peso)
export const inventoryItems = [
  {
    id: "INV-001",
    name: "Premium Dog Food 5kg",
    sku: "PDF-5KG-001",
    brand: "Pawsome Premium",
    supplier: "Pet Nutrition Co.",
    category: "Food",
    price: 1200.00,
    quantity: 50,
    expiration: "2026-12-10",
    status: "In stock",
    description: "High-quality nutrition for adult dogs",
  },
  {
    id: "INV-002",
    name: "Cat Kibble 2kg",
    sku: "CK-2KG-002",
    brand: "Whisker Delight",
    supplier: "Feline Nutrition Ltd.",
    category: "Food",
    price: 850.00,
    quantity: 30,
    expiration: "2026-11-05",
    status: "In stock",
    description: "Balanced diet for cats",
  },
  {
    id: "INV-003",
    name: "Leather Dog Collar",
    sku: "LDC-003",
    brand: "Pawsome Accessories",
    supplier: "Pet Style Co.",
    category: "Accessories",
    price: 450.00,
    quantity: 25,
    expiration: null,
    status: "In stock",
    description: "Durable leather collar with metal buckle",
  },
  {
    id: "INV-004",
    name: "Pet Shampoo 500ml",
    sku: "PS-500-004",
    brand: "Fresh & Clean",
    supplier: "Grooming Essentials",
    category: "Grooming",
    price: 280.00,
    quantity: 40,
    expiration: "2027-02-12",
    status: "In stock",
    description: "Gentle cleansing formula for pets",
  },
  {
    id: "INV-005",
    name: "Squeaky Toy Set",
    sku: "STS-005",
    brand: "PlayTime",
    supplier: "Pet Toys Inc.",
    category: "Toys",
    price: 180.00,
    quantity: 60,
    expiration: null,
    status: "In stock",
    description: "3-piece fun toy set for dogs",
  },
  {
    id: "INV-006",
    name: "Pet Carrier Small",
    sku: "PCS-006",
    brand: "Travel Paws",
    supplier: "Pet Travel Co.",
    category: "Accessories",
    price: 950.00,
    quantity: 0,
    expiration: null,
    status: "Out of stock",
    description: "Comfortable travel carrier for small pets",
  },
  {
    id: "INV-007",
    name: "Flea Treatment",
    sku: "FT-007",
    brand: "Guardian",
    supplier: "Pet Health Solutions",
    category: "Health",
    price: 380.00,
    quantity: 35,
    expiration: "2027-05-20",
    status: "In stock",
    description: "Monthly flea and tick prevention",
  },
  {
    id: "INV-008",
    name: "Puppy Starter Kit",
    sku: "PSK-008",
    brand: "Pawsome Beginnings",
    supplier: "Pet Nutrition Co.",
    category: "Food",
    price: 750.00,
    quantity: 20,
    expiration: "2026-10-15",
    status: "In stock",
    description: "Complete nutrition kit for puppies",
  },
  {
    id: "INV-009",
    name: "Pet Bed Medium",
    sku: "PBM-009",
    brand: "Cozy Paws",
    supplier: "Comfort Pet Supplies",
    category: "Accessories",
    price: 650.00,
    quantity: 15,
    expiration: null,
    status: "Low stock",
    description: "Soft cushioned bed for medium pets",
  },
  {
    id: "INV-010",
    name: "Dental Chew Sticks",
    sku: "DCS-010",
    brand: "Oral Care",
    supplier: "Pet Health Solutions",
    category: "Health",
    price: 220.00,
    quantity: 45,
    expiration: "2026-09-08",
    status: "In stock",
    description: "Dental care treats for dogs",
  },
  {
    id: "INV-011",
    name: "Full Grooming Service",
    sku: "SRV-001",
    brand: "Pawsome Grooming",
    supplier: "In-House",
    category: "Services",
    price: 650.00,
    quantity: 999,
    expiration: null,
    status: "In stock",
    description: "Bath, haircut, nail trim, ear cleaning",
  },
  {
    id: "INV-012",
    name: "Vet Consultation",
    sku: "SRV-002",
    brand: "Pawsome Vet",
    supplier: "In-House",
    category: "Services",
    price: 500.00,
    quantity: 999,
    expiration: null,
    status: "In stock",
    description: "Basic health check and consultation",
  },
];

// Pet store inventory history
export const inventoryHistory = [
  {
    id: "HIS-001",
    date: "2026-03-30 09:45",
    product: "Premium Dog Food 5kg",
    action: "Restocked",
    quantity: 24,
    user: "Admin",
    note: "Weekly delivery",
  },
  {
    id: "HIS-002",
    date: "2026-03-29 15:12",
    product: "Cat Kibble 2kg",
    action: "Sale",
    quantity: 8,
    user: "Cashier",
    note: "Customer purchase",
  },
  {
    id: "HIS-003",
    date: "2026-03-28 11:30",
    product: "Pet Shampoo 500ml",
    action: "Restocked",
    quantity: 30,
    user: "Admin",
    note: "Grooming supplies",
  },
  {
    id: "HIS-004",
    date: "2026-03-27 18:05",
    product: "Leather Dog Collar",
    action: "Sale",
    quantity: 5,
    user: "Cashier",
    note: "Evening sales",
  },
  {
    id: "HIS-005",
    date: "2026-03-26 14:20",
    product: "Flea Treatment",
    action: "Restocked",
    quantity: 20,
    user: "Admin",
    note: "Health products",
  },
  {
    id: "HIS-006",
    date: "2026-03-25 10:10",
    product: "Squeaky Toy Set",
    action: "Sale",
    quantity: 12,
    user: "Cashier",
    note: "Morning rush",
  },
];
